routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});


Route::resource('producto','ProductoController');

Route::get('/exportar', 'ProductoController@exportarProductos');

Route::resource('/login/user', 'CustomLoginController');

//Route::resource('/login', 'CustomLoginController');
Route::post('/login', 'CustomLoginController@loginUser');


Route::resource('/nuevo/usuario', 'UsuarioController');
Route::post('/registrar/usuario', 'UsuarioController@registrarUsuario');

Route::get('/usuarios', 'UsuarioController@allUsers');

app/Producto.php
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Producto extends Eloquent
{
    protected $connection = 'mongodb';
	protected $collection = 'producto';


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'nombre', 'categoria'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'rut', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Usuario.php
<?php

namespace App;

use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Usuario extends Eloquent
{
    //
    protected $connection = 'mongodb';
	protected $collection = 'user';


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'rut', 'password'
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CustomLoginController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Usuario;

use App\Producto;

use DB;

class CustomLoginController extends Controller
{
    //

    public function index(){


        return view('user.login');
    
    }

    public function loginUser(Request $request){

        $rut_user = $request->rut;
        $password_user = $request->password;

        $users = Usuario::where('rut', '=', $rut_user)->where('password', '=', $password_user)->count();


        if($users > 0 ){
        
            $producto = Producto::all();

            return view('producto.index', compact('producto'))
            ->with('i', request()->input('page,1'));

        }else{
            return view('user.login');
        }
        

    }
}

app/Http/Controllers/ProductoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Producto;

class ProductoController extends Controller
{
    //

    public function index(){

        $producto = Producto::all();

        return view('producto.index', compact('producto'))
        ->with('i', request()->input('page,1'));
    
    }

    public function create(){
        
        return view('producto.create');

    }

    public function store(Request $request){

        request()->validate([
            'nombre' => 'required',
            'categoria' => 'required',
        ]);

        Producto::create($request->all());

            return redirect()->route('producto.index')
            ->with('success','Producto Creado');

    }


    public function show(Producto $producto){

        return view('producto.show', compact('producto'));


    }

    public function edit(Producto $producto){

        return view('producto.edit', compact('producto'));

    }


    public function update(Request $request, Producto $producto){

        request()->validate([
            'nombre' => 'required',
            'categoria' => 'required',
        ]);


        $producto->update($request->all());


        return redirect()->route('producto.index')
                        ->with('success','Producto Actualizado');

    }

    public function destroy(Producto $producto){

        $producto->delete();

        return redirect()->route('producto.index')
        ->with('success','Producto Eliminado');


    }


    public function exportarProductos(){


        $phpWord = new \PhpOffice\PhpWord\PhpWord();

        $section = $phpWord->addSection();
        //$description = "Productos Registrados";

       // $section->addText($description);

       $producto = Producto::all();

       $table = $section->addTable();

       foreach ($producto as $prod) {
            $table->addRow();
            $table->addCell(1750)->addText("{$prod->nombre} - {$prod->categoria}");
        }
        
        

        $objWriter = \PhpOffice\PhpWord\IOFactory::createWriter($phpWord, 'Word2007');
        try {
            $objWriter->save(storage_path('Productos.docx'));
        } catch (Exception $e) {
        }


        return response()->download(storage_path('Productos.docx'));
        

        //print_r("doc");


    }
}

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Usuario;

use App\Producto;

use DB;


class UsuarioController extends Controller
{
    //

    public function index(){


        
        
        $usuarios = Usuario::all();
        return view('user.registro', compact('usuarios'));

        //return view('user.registro');

        /*
        $models = Usuario::raw(function($collection)
        {
            $usuarios = $collection->find();
            
            return view('user.registro', compact('usuarios'));
        });
        */
    
    }

    public function allUsers(){

        $usuarios = Usuario::all();

        return response()->json(array('usuarios' => $usuarios));

        /*

        $models = Usuario::raw(function($collection)
        {
            $usuarios = $collection->find();
            
            return view('user.registro', compact('usuarios'));
        });
        */

    }

    public function registrarUsuario(Request $request){

        $rut_user = $request->rut;
        $password_user = $request->password;

        $data = array('rut' => $rut_user, 'password' => $password_user);

        $insertData = DB::connection('mongodb')->collection('user')->insert($data);
        if($insertData){
            return view('user.registro');
        }


        //return view('user.registro');
    
    }
}

resources/views/layout.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Prueba CRUD</title>
	<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/handsontable@7.3.0/dist/handsontable.full.min.js"></script>
	<link href="https://cdn.jsdelivr.net/npm/handsontable@7.3.0/dist/handsontable.full.min.css" rel="stylesheet" media="screen">
	<meta name="csrf-token" content="{{ csrf_token() }}" />
</head>

<body>


<div class="container">
    @yield('content')
</div>


<!-- Login Js!-->
<script type="text/javascript" src="{{ asset('js/registro.js') }}"></script>

</body>
</html>

resources/views/producto/create.blade.php
@extends('layout')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Nuevo Producto</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('producto.index') }}"> Volver</a>
            </div>
        </div>
    </div>


    @if ($errors->any())
        <div class="alert alert-danger">
            <strong></strong> <br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('producto.store') }}" method="POST">
    	@csrf


         <div class="row">
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Nombre:</strong>
		            <input type="text" name="nombre" class="form-control" placeholder="Nombre">
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Categoria:</strong>
		            <textarea class="form-control" style="height:150px" name="categoria" placeholder="Categoria"></textarea>
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
		            <button type="submit" class="btn btn-primary">Guardar</button>
		    </div>
		</div>


    </form>


@endsection

resources/views/producto/edit.blade.php
@extends('layout')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Modificar Producto</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('producto.index') }}"> Volver</a>
            </div>
        </div>
    </div>


    @if ($errors->any())
        <div class="alert alert-danger">
            <strong></strong> <br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('producto.update',$producto->id) }}" method="POST">
    	@csrf
        @method('PUT')


         <div class="row">
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Nombre:</strong>
		            <input type="text" name="nombre" value="{{ $producto->nombre }}" class="form-control" placeholder="Nombre">
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Categoria:</strong>
		            <textarea class="form-control" style="height:150px" name="categoria" placeholder="Categoria">{{ $producto->categoria }}</textarea>
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
		      <button type="submit" class="btn btn-primary">Guardar</button>
		    </div>
		</div>


    </form>


@endsection

resources/views/producto/index.blade.php
@extends('layout')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Productos</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('producto.create') }}"> Crear Nuevo Producto</a>
                
            </div>
        </div>
    </div>


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif


    <table class="table table-bordered">
        <tr>
            <th>N°</th>
            <th>Nombre</th>
            <th>Categoria</th>
            <th width="280px">Acción</th>
        </tr>
	    @foreach ($producto as $prod)
	    <tr>
	        <td>{{ ++$i }}</td>
	        <td>{{ $prod->nombre }}</td>
	        <td>{{ $prod->categoria }}</td>
	        <td>
                <form action="{{ route('producto.destroy',$prod->id) }}" method="POST">
                    <a class="btn btn-info" href="{{ route('producto.show',$prod->id) }}">Ver</a>
                    <a class="btn btn-primary" href="{{ route('producto.edit',$prod->id) }}">Modificar</a>
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                </form>
	        </td>
	    </tr>
	    @endforeach
    </table>

    <center><a class="btn btn-info" href="{{ ('/exportar') }}"> Exportar Productos</a></center>


@endsection

resources/views/producto/show.blade.php
@extends('layout')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Ver Producto</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('producto.index') }}"> Volver</a>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nombre:</strong>
                {{ $producto->nombre }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Categoria:</strong>
                {{ $producto->categoria }}
            </div>
        </div>
    </div>
@endsection

resources/views/user/login.blade.php
@extends('layout')


@section('content')
<!--
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Nuevo Producto</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('producto.index') }}"> Volver</a>
            </div>
        </div>
    </div>
    !-->


    @if ($errors->any())
        <div class="alert alert-danger">
            <strong></strong> <br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ ('/login') }}" method="POST">
    	@csrf


         <div class="row">
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>RUT:</strong>
		            <input type="text" name="rut" id="rut" class="form-control" placeholder="RUT">
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Contraseña:</strong>
		            <input type="password" class="form-control" name="password"  id="password" placeholder="Contraseña">
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Ingresar</button>
                
		    </div>
		</div>


    </form>

    <br>


    

<center><a href="{{('/nuevo/usuario')}}"><button type="submit" class="btn btn-success">Registrar</button></a></center>



    
    


@endsection

resources/views/user/registro.blade.php
@extends('layout')


@section('content')


    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Nuevo Usuario</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('producto.index') }}"> Volver</a>
            </div>
        </div>
    </div>
   




    @if ($errors->any())
        <div class="alert alert-danger">
            <strong></strong> <br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form>
    	@csrf


         <div class="row">
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>RUT:</strong>
		            <input type="text" name="rut" id="rut" class="form-control" placeholder="RUT">
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Contraseña:</strong>
		            <input type="password" class="form-control" name="password"  id="password" placeholder="Contraseña">
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button onclick="RegistrarUsuario();" class="btn btn-primary">Guardar</button>
                
		    </div>
		</div>


    </form>

    <div id="example"></div>

    





    
    


@endsection